/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    jobsCompleted: bigint;
    month: string;
    goalsAchieved: bigint;
    year: bigint;
    paidInvoices: bigint;
    vatCollected: number;
    totalExpenses: number;
    goalsMissed: bigint;
    pendingInvoices: bigint;
    totalRevenue: number;
    netProfit: number;
}
export interface JobRevenueEntry {
    revenue: number;
    clientName: string;
    date: bigint;
    jobId: bigint;
    sector: string;
}
export interface UserPreferences {
    metricFilters: Array<string>;
    preferredLayout: string;
    navigationPreferences: string;
    darkMode: boolean;
    displayPreferences: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Job {
    id: bigint;
    customerInfo: CustomerInfo;
    revenue: number;
    clientName: string;
    date: bigint;
    costs: number;
    sector: string;
    cleanProfit: number;
}
export interface FundBalance {
    balance: number;
    name: string;
    fundId: bigint;
    recentTransactions: Array<FundTransaction>;
    fundType: FundType;
}
export interface Quote {
    id: bigint;
    customerInfo: CustomerInfo;
    finalPrice: number;
    volumeDiscount: number;
    date: bigint;
    town: string;
    sector: string;
    subSector?: string;
    grandTotal: number;
    addOns: Array<string>;
    vatAmount: number;
    basePrice: number;
    services: Array<Service>;
    nightService: boolean;
    chargeDescription: string;
}
export interface DroneWashDashboardInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addExpense(amount: number, category: string, date: bigint, additionalInfo: string): Promise<bigint>;
    addJob(revenue: number, date: bigint, sector: string, clientName: string, customerInfo: CustomerInfo, cleanProfit: number, costs: number): Promise<bigint>;
    addMaintenanceFundInflow(amount: number, description: string): Promise<bigint>;
    addMonthlyGoal(month: string, year: bigint, description: string, targetValue: number): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backupData(): Promise<BackupData>;
    createContract(contractName: string, clientName: string, clientEmail: string, clientPhone: string, clientCompany: string, servicesCovered: Array<string>, areaTier: string, agreedPrices: Array<[string, number]>, contractStatus: string, startDate: bigint, endDate: bigint | null): Promise<bigint>;
    createInvoice(customerName: string, customerEmail: string, quoteId: bigint, totalAmount: number): Promise<bigint>;
    createQuote(sector: string, services: Array<Service>, basePrice: number, addOns: Array<string>, volumeDiscount: number, nightService: boolean, finalPrice: number, town: string, subSector: string | null, customerInfo: CustomerInfo, chargeDescription: string, vatAmount: number, grandTotal: number): Promise<bigint>;
    deleteContract(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteJob(id: bigint): Promise<void>;
    deleteQuote(id: bigint): Promise<void>;
    getActiveContracts(): Promise<Array<Contract>>;
    getAllContracts(): Promise<Array<Contract>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllJobs(): Promise<Array<Job>>;
    getAllMonthlyGoals(): Promise<Array<MonthlyGoal>>;
    getAllQuotes(): Promise<Array<Quote>>;
    getAllServiceRates(): Promise<Array<[string, Array<[string, number]>]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContract(id: bigint): Promise<Contract | null>;
    getContractByClientName(clientName: string): Promise<Contract | null>;
    getExpense(id: bigint): Promise<Expense | null>;
    getFinancialMetrics(): Promise<FinancialMetrics>;
    getFinancialMetricsDetailed(): Promise<FinancialMetricsDetailed>;
    getInternalQuoteView(id: bigint): Promise<InternalQuoteView>;
    getInvoice(id: bigint): Promise<Invoice | null>;
    getJob(id: bigint): Promise<Job | null>;
    getMaintenanceFundBalance(): Promise<number>;
    getMonthlyExpenses(): Promise<Array<[string, number]>>;
    getMonthlyGoalsByMonthYear(month: string, year: bigint): Promise<Array<MonthlyGoal>>;
    getMonthlyReport(month: string, year: bigint): Promise<MonthlyReport>;
    getMonthlyRevenue(): Promise<Array<[string, number]>>;
    getProfitProjection(): Promise<Array<[bigint, number]>>;
    getQuote(id: bigint): Promise<Quote | null>;
    getServiceRate(serviceType: string, areaTier: string): Promise<number>;
    getStandardizedServices(): Promise<Array<ServiceType>>;
    getUserPreferences(): Promise<UserPreferences | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    resetMaintenanceFund(): Promise<void>;
    safeResetMaintenanceFundWithCashout(): Promise<number>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveUserPreferences(preferences: UserPreferences): Promise<void>;
    setServiceRate(serviceType: string, areaTier: string, rate: number): Promise<void>;
    updateContract(id: bigint, contractName: string, clientName: string, clientEmail: string, clientPhone: string, clientCompany: string, servicesCovered: Array<string>, areaTier: string, agreedPrices: Array<[string, number]>, contractStatus: string, startDate: bigint, endDate: bigint | null): Promise<void>;
    updateExpense(id: bigint, amount: number, category: string, date: bigint, additionalInfo: string): Promise<void>;
    updateInvoice(id: bigint, customerName: string, customerEmail: string, quoteId: bigint, totalAmount: number, status: string): Promise<void>;
    updateInvoiceStatus(invoiceId: bigint, status: string): Promise<void>;
    updateJob(id: bigint, revenue: number, date: bigint, sector: string, clientName: string, customerInfo: CustomerInfo, cleanProfit: number, costs: number): Promise<void>;
    updateMonthlyGoal(id: bigint, achieved: boolean, actualValue: number): Promise<void>;
    updateQuote(id: bigint, sector: string, services: Array<Service>, basePrice: number, addOns: Array<string>, volumeDiscount: number, nightService: boolean, finalPrice: number, town: string, subSector: string | null, customerInfo: CustomerInfo, chargeDescription: string, vatAmount: number, grandTotal: number): Promise<void>;
}
export interface Contract {
    id: bigint;
    endDate?: bigint;
    clientName: string;
    createdBy: Principal;
    clientEmail: string;
    clientCompany: string;
    contractName: string;
    lastUpdated: bigint;
    agreedPrices: Array<[string, number]>;
    createdDate: bigint;
    clientPhone: string;
    areaTier: string;
    servicesCovered: Array<string>;
    contractStatus: string;
    startDate: bigint;
}
export interface ExpenseEntry {
    additionalInfo: string;
    expenseId: bigint;
    date: bigint;
    category: string;
    amount: number;
}
export interface MaintenanceFundLedger {
    id: bigint;
    transactionType: string;
    date: bigint;
    relatedJobId?: bigint;
    fundId: bigint;
    fundType: FundType;
    remainingBalance: number;
    relatedExpenseId?: bigint;
    amount: number;
    purpose: string;
}
export interface Service {
    serviceType: string;
    rate: number;
    quantity: number;
}
export interface MaintenanceFundStatus {
    balance: number;
    totalCollected: number;
    fundId?: bigint;
    totalSpent: number;
    recentEntries: Array<MaintenanceFundLedger>;
}
export interface Invoice {
    id: bigint;
    customerName: string;
    status: string;
    date: bigint;
    quoteId: bigint;
    totalAmount: number;
    customerEmail: string;
}
export interface FundTransaction {
    id: bigint;
    transactionType: string;
    date: bigint;
    description: string;
    relatedJobId?: bigint;
    fundId: bigint;
    fundType: FundType;
    remainingBalance: number;
    relatedExpenseId?: bigint;
    category: string;
    amount: number;
}
export interface FinancialMetricsDetailed {
    totalRevenueYTD: number;
    expenseBreakdown: Array<ExpenseEntry>;
    breakEvenProgress: number;
    investmentRemaining: number;
    revenueBreakdown: Array<JobRevenueEntry>;
    maintenanceFundStatus: MaintenanceFundStatus;
    fundBalances: Array<FundBalance>;
    netProfit: number;
}
export interface Expense {
    id: bigint;
    additionalInfo: string;
    date: bigint;
    category: string;
    amount: number;
}
export interface MonthlyGoal {
    id: bigint;
    month: string;
    achieved: boolean;
    year: bigint;
    description: string;
    actualValue: number;
    targetValue: number;
}
export interface BackupData {
    jobs: Array<Job>;
    expenses: Array<Expense>;
    userProfiles: Array<[Principal, UserProfile]>;
    contracts: Array<Contract>;
    serviceRates: Array<[string, Array<[string, number]>]>;
    timestamp: bigint;
    invoices: Array<Invoice>;
    quotes: Array<Quote>;
}
export interface CostBreakdown {
    revenue: number;
    cogs: number;
    additionalPilot: number;
    opEx: number;
    vanFuel: number;
    chemicals: number;
    profitMargin: number;
    generatorFuel: number;
}
export interface FinancialMetrics {
    totalRevenueYTD: number;
    breakEvenProgress: number;
    investmentRemaining: number;
    netProfit: number;
}
export interface CustomerInfo {
    additionalInfo: string;
    jobType: string;
    name: string;
    town: string;
    coordinates: string;
}
export interface InternalQuoteView {
    quote: Quote;
    costBreakdown: CostBreakdown;
}
export interface UserProfile {
    name: string;
    role: UserRole;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FundType {
    main = "main",
    investment = "investment",
    maintenance = "maintenance",
    salaries = "salaries"
}
export enum ServiceType {
    windowCleaning = "windowCleaning",
    solarPanelCleaning = "solarPanelCleaning",
    facadeWallCleaning = "facadeWallCleaning",
    roofCleaning = "roofCleaning",
    fullBuildingCleaning = "fullBuildingCleaning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface extends DroneWashDashboardInterface {
}
import type { BackupData as _BackupData, Contract as _Contract, CostBreakdown as _CostBreakdown, CustomerInfo as _CustomerInfo, Expense as _Expense, ExpenseEntry as _ExpenseEntry, FinancialMetricsDetailed as _FinancialMetricsDetailed, FundBalance as _FundBalance, FundTransaction as _FundTransaction, FundType as _FundType, InternalQuoteView as _InternalQuoteView, Invoice as _Invoice, Job as _Job, JobRevenueEntry as _JobRevenueEntry, MaintenanceFundLedger as _MaintenanceFundLedger, MaintenanceFundStatus as _MaintenanceFundStatus, Quote as _Quote, Service as _Service, ServiceType as _ServiceType, UserPreferences as _UserPreferences, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addExpense(arg0: number, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addJob(arg0: number, arg1: bigint, arg2: string, arg3: string, arg4: CustomerInfo, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addMaintenanceFundInflow(arg0: number, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMaintenanceFundInflow(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMaintenanceFundInflow(arg0, arg1);
            return result;
        }
    }
    async addMonthlyGoal(arg0: string, arg1: bigint, arg2: string, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMonthlyGoal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMonthlyGoal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backupData(): Promise<BackupData> {
        if (this.processError) {
            try {
                const result = await this.actor.backupData();
                return from_candid_BackupData_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backupData();
            return from_candid_BackupData_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createContract(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: string, arg7: Array<[string, number]>, arg8: string, arg9: bigint, arg10: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async createInvoice(arg0: string, arg1: string, arg2: bigint, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createQuote(arg0: string, arg1: Array<Service>, arg2: number, arg3: Array<string>, arg4: number, arg5: boolean, arg6: number, arg7: string, arg8: string | null, arg9: CustomerInfo, arg10: string, arg11: number, arg12: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuote(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuote(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async deleteContract(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContract(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContract(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteQuote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuote(arg0);
            return result;
        }
    }
    async getActiveContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveContracts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveContracts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContracts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContracts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return result;
        }
    }
    async getAllMonthlyGoals(): Promise<Array<MonthlyGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlyGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlyGoals();
            return result;
        }
    }
    async getAllQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotes();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotes();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServiceRates(): Promise<Array<[string, Array<[string, number]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceRates();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: bigint): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractByClientName(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractByClientName(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractByClientName(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpense(arg0: bigint): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialMetrics(): Promise<FinancialMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialMetrics();
            return result;
        }
    }
    async getFinancialMetricsDetailed(): Promise<FinancialMetricsDetailed> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialMetricsDetailed();
                return from_candid_FinancialMetricsDetailed_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialMetricsDetailed();
            return from_candid_FinancialMetricsDetailed_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInternalQuoteView(arg0: bigint): Promise<InternalQuoteView> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternalQuoteView(arg0);
                return from_candid_InternalQuoteView_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternalQuoteView(arg0);
            return from_candid_InternalQuoteView_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceFundBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceFundBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceFundBalance();
            return result;
        }
    }
    async getMonthlyExpenses(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyExpenses();
            return result;
        }
    }
    async getMonthlyGoalsByMonthYear(arg0: string, arg1: bigint): Promise<Array<MonthlyGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyGoalsByMonthYear(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyGoalsByMonthYear(arg0, arg1);
            return result;
        }
    }
    async getMonthlyReport(arg0: string, arg1: bigint): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getMonthlyRevenue(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyRevenue();
            return result;
        }
    }
    async getProfitProjection(): Promise<Array<[bigint, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitProjection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitProjection();
            return result;
        }
    }
    async getQuote(arg0: bigint): Promise<Quote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuote(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuote(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceRate(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceRate(arg0, arg1);
            return result;
        }
    }
    async getStandardizedServices(): Promise<Array<ServiceType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandardizedServices();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandardizedServices();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPreferences(): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetMaintenanceFund(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMaintenanceFund();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMaintenanceFund();
            return result;
        }
    }
    async safeResetMaintenanceFundWithCashout(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.safeResetMaintenanceFundWithCashout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.safeResetMaintenanceFundWithCashout();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveUserPreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserPreferences(arg0);
            return result;
        }
    }
    async setServiceRate(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setServiceRate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setServiceRate(arg0, arg1, arg2);
            return result;
        }
    }
    async updateContract(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<string>, arg7: string, arg8: Array<[string, number]>, arg9: string, arg10: bigint, arg11: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContract(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: number, arg2: string, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: number, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateInvoiceStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(arg0, arg1);
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: number, arg2: bigint, arg3: string, arg4: string, arg5: CustomerInfo, arg6: number, arg7: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateMonthlyGoal(arg0: bigint, arg1: boolean, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async updateQuote(arg0: bigint, arg1: string, arg2: Array<Service>, arg3: number, arg4: Array<string>, arg5: number, arg6: boolean, arg7: number, arg8: string, arg9: string | null, arg10: CustomerInfo, arg11: string, arg12: number, arg13: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuote(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, arg13);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuote(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, arg13);
            return result;
        }
    }
}
function from_candid_BackupData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackupData): BackupData {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialMetricsDetailed_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialMetricsDetailed): FinancialMetricsDetailed {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_FundBalance_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundBalance): FundBalance {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_FundTransaction_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundTransaction): FundTransaction {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_FundType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundType): FundType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_InternalQuoteView_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InternalQuoteView): InternalQuoteView {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceFundLedger_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceFundLedger): MaintenanceFundLedger {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MaintenanceFundStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaintenanceFundStatus): MaintenanceFundStatus {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Quote_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contract]): Contract | null {
    return value.length === 0 ? null : from_candid_Contract_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expense]): Expense | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quote]): Quote | null {
    return value.length === 0 ? null : from_candid_Quote_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobs: Array<_Job>;
    expenses: Array<_Expense>;
    userProfiles: Array<[Principal, _UserProfile]>;
    contracts: Array<_Contract>;
    serviceRates: Array<[string, Array<[string, number]>]>;
    timestamp: bigint;
    invoices: Array<_Invoice>;
    quotes: Array<_Quote>;
}): {
    jobs: Array<Job>;
    expenses: Array<Expense>;
    userProfiles: Array<[Principal, UserProfile]>;
    contracts: Array<Contract>;
    serviceRates: Array<[string, Array<[string, number]>]>;
    timestamp: bigint;
    invoices: Array<Invoice>;
    quotes: Array<Quote>;
} {
    return {
        jobs: value.jobs,
        expenses: value.expenses,
        userProfiles: from_candid_vec_n12(_uploadFile, _downloadFile, value.userProfiles),
        contracts: from_candid_vec_n18(_uploadFile, _downloadFile, value.contracts),
        serviceRates: value.serviceRates,
        timestamp: value.timestamp,
        invoices: value.invoices,
        quotes: from_candid_vec_n22(_uploadFile, _downloadFile, value.quotes)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
    email: string;
}): {
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    endDate: [] | [bigint];
    clientName: string;
    createdBy: Principal;
    clientEmail: string;
    clientCompany: string;
    contractName: string;
    lastUpdated: bigint;
    agreedPrices: Array<[string, number]>;
    createdDate: bigint;
    clientPhone: string;
    areaTier: string;
    servicesCovered: Array<string>;
    contractStatus: string;
    startDate: bigint;
}): {
    id: bigint;
    endDate?: bigint;
    clientName: string;
    createdBy: Principal;
    clientEmail: string;
    clientCompany: string;
    contractName: string;
    lastUpdated: bigint;
    agreedPrices: Array<[string, number]>;
    createdDate: bigint;
    clientPhone: string;
    areaTier: string;
    servicesCovered: Array<string>;
    contractStatus: string;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.endDate)),
        clientName: value.clientName,
        createdBy: value.createdBy,
        clientEmail: value.clientEmail,
        clientCompany: value.clientCompany,
        contractName: value.contractName,
        lastUpdated: value.lastUpdated,
        agreedPrices: value.agreedPrices,
        createdDate: value.createdDate,
        clientPhone: value.clientPhone,
        areaTier: value.areaTier,
        servicesCovered: value.servicesCovered,
        contractStatus: value.contractStatus,
        startDate: value.startDate
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerInfo: _CustomerInfo;
    finalPrice: number;
    volumeDiscount: number;
    date: bigint;
    town: string;
    sector: string;
    subSector: [] | [string];
    grandTotal: number;
    addOns: Array<string>;
    vatAmount: number;
    basePrice: number;
    services: Array<_Service>;
    nightService: boolean;
    chargeDescription: string;
}): {
    id: bigint;
    customerInfo: CustomerInfo;
    finalPrice: number;
    volumeDiscount: number;
    date: bigint;
    town: string;
    sector: string;
    subSector?: string;
    grandTotal: number;
    addOns: Array<string>;
    vatAmount: number;
    basePrice: number;
    services: Array<Service>;
    nightService: boolean;
    chargeDescription: string;
} {
    return {
        id: value.id,
        customerInfo: value.customerInfo,
        finalPrice: value.finalPrice,
        volumeDiscount: value.volumeDiscount,
        date: value.date,
        town: value.town,
        sector: value.sector,
        subSector: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.subSector)),
        grandTotal: value.grandTotal,
        addOns: value.addOns,
        vatAmount: value.vatAmount,
        basePrice: value.basePrice,
        services: value.services,
        nightService: value.nightService,
        chargeDescription: value.chargeDescription
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalRevenueYTD: number;
    expenseBreakdown: Array<_ExpenseEntry>;
    breakEvenProgress: number;
    investmentRemaining: number;
    revenueBreakdown: Array<_JobRevenueEntry>;
    maintenanceFundStatus: _MaintenanceFundStatus;
    fundBalances: Array<_FundBalance>;
    netProfit: number;
}): {
    totalRevenueYTD: number;
    expenseBreakdown: Array<ExpenseEntry>;
    breakEvenProgress: number;
    investmentRemaining: number;
    revenueBreakdown: Array<JobRevenueEntry>;
    maintenanceFundStatus: MaintenanceFundStatus;
    fundBalances: Array<FundBalance>;
    netProfit: number;
} {
    return {
        totalRevenueYTD: value.totalRevenueYTD,
        expenseBreakdown: value.expenseBreakdown,
        breakEvenProgress: value.breakEvenProgress,
        investmentRemaining: value.investmentRemaining,
        revenueBreakdown: value.revenueBreakdown,
        maintenanceFundStatus: from_candid_MaintenanceFundStatus_n33(_uploadFile, _downloadFile, value.maintenanceFundStatus),
        fundBalances: from_candid_vec_n40(_uploadFile, _downloadFile, value.fundBalances),
        netProfit: value.netProfit
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    totalCollected: number;
    fundId: [] | [bigint];
    totalSpent: number;
    recentEntries: Array<_MaintenanceFundLedger>;
}): {
    balance: number;
    totalCollected: number;
    fundId?: bigint;
    totalSpent: number;
    recentEntries: Array<MaintenanceFundLedger>;
} {
    return {
        balance: value.balance,
        totalCollected: value.totalCollected,
        fundId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.fundId)),
        totalSpent: value.totalSpent,
        recentEntries: from_candid_vec_n35(_uploadFile, _downloadFile, value.recentEntries)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: string;
    date: bigint;
    relatedJobId: [] | [bigint];
    fundId: bigint;
    fundType: _FundType;
    remainingBalance: number;
    relatedExpenseId: [] | [bigint];
    amount: number;
    purpose: string;
}): {
    id: bigint;
    transactionType: string;
    date: bigint;
    relatedJobId?: bigint;
    fundId: bigint;
    fundType: FundType;
    remainingBalance: number;
    relatedExpenseId?: bigint;
    amount: number;
    purpose: string;
} {
    return {
        id: value.id,
        transactionType: value.transactionType,
        date: value.date,
        relatedJobId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedJobId)),
        fundId: value.fundId,
        fundType: from_candid_FundType_n38(_uploadFile, _downloadFile, value.fundType),
        remainingBalance: value.remainingBalance,
        relatedExpenseId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedExpenseId)),
        amount: value.amount,
        purpose: value.purpose
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    name: string;
    fundId: bigint;
    recentTransactions: Array<_FundTransaction>;
    fundType: _FundType;
}): {
    balance: number;
    name: string;
    fundId: bigint;
    recentTransactions: Array<FundTransaction>;
    fundType: FundType;
} {
    return {
        balance: value.balance,
        name: value.name,
        fundId: value.fundId,
        recentTransactions: from_candid_vec_n43(_uploadFile, _downloadFile, value.recentTransactions),
        fundType: from_candid_FundType_n38(_uploadFile, _downloadFile, value.fundType)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: string;
    date: bigint;
    description: string;
    relatedJobId: [] | [bigint];
    fundId: bigint;
    fundType: _FundType;
    remainingBalance: number;
    relatedExpenseId: [] | [bigint];
    category: string;
    amount: number;
}): {
    id: bigint;
    transactionType: string;
    date: bigint;
    description: string;
    relatedJobId?: bigint;
    fundId: bigint;
    fundType: FundType;
    remainingBalance: number;
    relatedExpenseId?: bigint;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: value.transactionType,
        date: value.date,
        description: value.description,
        relatedJobId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedJobId)),
        fundId: value.fundId,
        fundType: from_candid_FundType_n38(_uploadFile, _downloadFile, value.fundType),
        remainingBalance: value.remainingBalance,
        relatedExpenseId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedExpenseId)),
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quote: _Quote;
    costBreakdown: _CostBreakdown;
}): {
    quote: Quote;
    costBreakdown: CostBreakdown;
} {
    return {
        quote: from_candid_Quote_n23(_uploadFile, _downloadFile, value.quote),
        costBreakdown: value.costBreakdown
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    main: null;
} | {
    investment: null;
} | {
    maintenance: null;
} | {
    salaries: null;
}): FundType {
    return "main" in value ? FundType.main : "investment" in value ? FundType.investment : "maintenance" in value ? FundType.maintenance : "salaries" in value ? FundType.salaries : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    windowCleaning: null;
} | {
    solarPanelCleaning: null;
} | {
    facadeWallCleaning: null;
} | {
    roofCleaning: null;
} | {
    fullBuildingCleaning: null;
}): ServiceType {
    return "windowCleaning" in value ? ServiceType.windowCleaning : "solarPanelCleaning" in value ? ServiceType.solarPanelCleaning : "facadeWallCleaning" in value ? ServiceType.facadeWallCleaning : "roofCleaning" in value ? ServiceType.roofCleaning : "fullBuildingCleaning" in value ? ServiceType.fullBuildingCleaning : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Array<Contract> {
    return value.map((x)=>from_candid_Contract_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaintenanceFundLedger>): Array<MaintenanceFundLedger> {
    return value.map((x)=>from_candid_MaintenanceFundLedger_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FundBalance>): Array<FundBalance> {
    return value.map((x)=>from_candid_FundBalance_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FundTransaction>): Array<FundTransaction> {
    return value.map((x)=>from_candid_FundTransaction_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceType>): Array<ServiceType> {
    return value.map((x)=>from_candid_ServiceType_n52(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n8(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
