/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CustomerInfo = IDL.Record({
  'additionalInfo' : IDL.Text,
  'jobType' : IDL.Text,
  'name' : IDL.Text,
  'town' : IDL.Text,
  'coordinates' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'customerInfo' : CustomerInfo,
  'revenue' : IDL.Float64,
  'clientName' : IDL.Text,
  'date' : IDL.Int,
  'costs' : IDL.Float64,
  'sector' : IDL.Text,
  'cleanProfit' : IDL.Float64,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'additionalInfo' : IDL.Text,
  'date' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Opt(IDL.Int),
  'clientName' : IDL.Text,
  'createdBy' : IDL.Principal,
  'clientEmail' : IDL.Text,
  'clientCompany' : IDL.Text,
  'contractName' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'agreedPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'createdDate' : IDL.Int,
  'clientPhone' : IDL.Text,
  'areaTier' : IDL.Text,
  'servicesCovered' : IDL.Vec(IDL.Text),
  'contractStatus' : IDL.Text,
  'startDate' : IDL.Int,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Int,
  'quoteId' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'customerEmail' : IDL.Text,
});
export const Service = IDL.Record({
  'serviceType' : IDL.Text,
  'rate' : IDL.Float64,
  'quantity' : IDL.Float64,
});
export const Quote = IDL.Record({
  'id' : IDL.Nat,
  'customerInfo' : CustomerInfo,
  'finalPrice' : IDL.Float64,
  'volumeDiscount' : IDL.Float64,
  'date' : IDL.Int,
  'town' : IDL.Text,
  'sector' : IDL.Text,
  'subSector' : IDL.Opt(IDL.Text),
  'grandTotal' : IDL.Float64,
  'addOns' : IDL.Vec(IDL.Text),
  'vatAmount' : IDL.Float64,
  'basePrice' : IDL.Float64,
  'services' : IDL.Vec(Service),
  'nightService' : IDL.Bool,
  'chargeDescription' : IDL.Text,
});
export const BackupData = IDL.Record({
  'jobs' : IDL.Vec(Job),
  'expenses' : IDL.Vec(Expense),
  'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'contracts' : IDL.Vec(Contract),
  'serviceRates' : IDL.Vec(
    IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)))
  ),
  'timestamp' : IDL.Int,
  'invoices' : IDL.Vec(Invoice),
  'quotes' : IDL.Vec(Quote),
});
export const MonthlyGoal = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Text,
  'achieved' : IDL.Bool,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'actualValue' : IDL.Float64,
  'targetValue' : IDL.Float64,
});
export const FinancialMetrics = IDL.Record({
  'totalRevenueYTD' : IDL.Float64,
  'breakEvenProgress' : IDL.Float64,
  'investmentRemaining' : IDL.Float64,
  'netProfit' : IDL.Float64,
});
export const ExpenseEntry = IDL.Record({
  'additionalInfo' : IDL.Text,
  'expenseId' : IDL.Nat,
  'date' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const JobRevenueEntry = IDL.Record({
  'revenue' : IDL.Float64,
  'clientName' : IDL.Text,
  'date' : IDL.Int,
  'jobId' : IDL.Nat,
  'sector' : IDL.Text,
});
export const FundType = IDL.Variant({
  'main' : IDL.Null,
  'investment' : IDL.Null,
  'maintenance' : IDL.Null,
  'salaries' : IDL.Null,
});
export const MaintenanceFundLedger = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Text,
  'date' : IDL.Int,
  'relatedJobId' : IDL.Opt(IDL.Nat),
  'fundId' : IDL.Nat,
  'fundType' : FundType,
  'remainingBalance' : IDL.Float64,
  'relatedExpenseId' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Float64,
  'purpose' : IDL.Text,
});
export const MaintenanceFundStatus = IDL.Record({
  'balance' : IDL.Float64,
  'totalCollected' : IDL.Float64,
  'fundId' : IDL.Opt(IDL.Nat),
  'totalSpent' : IDL.Float64,
  'recentEntries' : IDL.Vec(MaintenanceFundLedger),
});
export const FundTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'relatedJobId' : IDL.Opt(IDL.Nat),
  'fundId' : IDL.Nat,
  'fundType' : FundType,
  'remainingBalance' : IDL.Float64,
  'relatedExpenseId' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FundBalance = IDL.Record({
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'fundId' : IDL.Nat,
  'recentTransactions' : IDL.Vec(FundTransaction),
  'fundType' : FundType,
});
export const FinancialMetricsDetailed = IDL.Record({
  'totalRevenueYTD' : IDL.Float64,
  'expenseBreakdown' : IDL.Vec(ExpenseEntry),
  'breakEvenProgress' : IDL.Float64,
  'investmentRemaining' : IDL.Float64,
  'revenueBreakdown' : IDL.Vec(JobRevenueEntry),
  'maintenanceFundStatus' : MaintenanceFundStatus,
  'fundBalances' : IDL.Vec(FundBalance),
  'netProfit' : IDL.Float64,
});
export const CostBreakdown = IDL.Record({
  'revenue' : IDL.Float64,
  'cogs' : IDL.Float64,
  'additionalPilot' : IDL.Float64,
  'opEx' : IDL.Float64,
  'vanFuel' : IDL.Float64,
  'chemicals' : IDL.Float64,
  'profitMargin' : IDL.Float64,
  'generatorFuel' : IDL.Float64,
});
export const InternalQuoteView = IDL.Record({
  'quote' : Quote,
  'costBreakdown' : CostBreakdown,
});
export const MonthlyReport = IDL.Record({
  'jobsCompleted' : IDL.Nat,
  'month' : IDL.Text,
  'goalsAchieved' : IDL.Nat,
  'year' : IDL.Nat,
  'paidInvoices' : IDL.Nat,
  'vatCollected' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'goalsMissed' : IDL.Nat,
  'pendingInvoices' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'netProfit' : IDL.Float64,
});
export const ServiceType = IDL.Variant({
  'windowCleaning' : IDL.Null,
  'solarPanelCleaning' : IDL.Null,
  'facadeWallCleaning' : IDL.Null,
  'roofCleaning' : IDL.Null,
  'fullBuildingCleaning' : IDL.Null,
});
export const UserPreferences = IDL.Record({
  'metricFilters' : IDL.Vec(IDL.Text),
  'preferredLayout' : IDL.Text,
  'navigationPreferences' : IDL.Text,
  'darkMode' : IDL.Bool,
  'displayPreferences' : IDL.Text,
});
export const DroneWashDashboard = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addExpense' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addJob' : IDL.Func(
      [
        IDL.Float64,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        CustomerInfo,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'addMonthlyGoal' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backupData' : IDL.Func([], [BackupData], []),
  'createContract' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
      ],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createQuote' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(Service),
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        CustomerInfo,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteContract' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'deleteQuote' : IDL.Func([IDL.Nat], [], []),
  'getActiveContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getAllMonthlyGoals' : IDL.Func([], [IDL.Vec(MonthlyGoal)], ['query']),
  'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getAllServiceRates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContract' : IDL.Func([IDL.Nat], [IDL.Opt(Contract)], ['query']),
  'getContractByClientName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Contract)],
      ['query'],
    ),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getFinancialMetrics' : IDL.Func([], [FinancialMetrics], ['query']),
  'getFinancialMetricsDetailed' : IDL.Func(
      [],
      [FinancialMetricsDetailed],
      ['query'],
    ),
  'getInternalQuoteView' : IDL.Func([IDL.Nat], [InternalQuoteView], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getMonthlyExpenses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getMonthlyGoalsByMonthYear' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(MonthlyGoal)],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [MonthlyReport],
      ['query'],
    ),
  'getMonthlyRevenue' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'getProfitProjection' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getQuote' : IDL.Func([IDL.Nat], [IDL.Opt(Quote)], ['query']),
  'getServiceRate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], ['query']),
  'getStandardizedServices' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
  'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetMaintenanceFund' : IDL.Func([], [], []),
  'safeResetMaintenanceFundWithCashout' : IDL.Func([], [IDL.Float64], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserPreferences' : IDL.Func([UserPreferences], [], []),
  'setServiceRate' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'updateContract' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
      [],
      [],
    ),
  'updateInvoice' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        CustomerInfo,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateMonthlyGoal' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Float64], [], []),
  'updateQuote' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(Service),
        IDL.Float64,
        IDL.Vec(IDL.Text),
        IDL.Float64,
        IDL.Bool,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Text),
        CustomerInfo,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlService = DroneWashDashboard;

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CustomerInfo = IDL.Record({
    'additionalInfo' : IDL.Text,
    'jobType' : IDL.Text,
    'name' : IDL.Text,
    'town' : IDL.Text,
    'coordinates' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'customerInfo' : CustomerInfo,
    'revenue' : IDL.Float64,
    'clientName' : IDL.Text,
    'date' : IDL.Int,
    'costs' : IDL.Float64,
    'sector' : IDL.Text,
    'cleanProfit' : IDL.Float64,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'additionalInfo' : IDL.Text,
    'date' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Opt(IDL.Int),
    'clientName' : IDL.Text,
    'createdBy' : IDL.Principal,
    'clientEmail' : IDL.Text,
    'clientCompany' : IDL.Text,
    'contractName' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'agreedPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'createdDate' : IDL.Int,
    'clientPhone' : IDL.Text,
    'areaTier' : IDL.Text,
    'servicesCovered' : IDL.Vec(IDL.Text),
    'contractStatus' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Int,
    'quoteId' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'customerEmail' : IDL.Text,
  });
  const Service = IDL.Record({
    'serviceType' : IDL.Text,
    'rate' : IDL.Float64,
    'quantity' : IDL.Float64,
  });
  const Quote = IDL.Record({
    'id' : IDL.Nat,
    'customerInfo' : CustomerInfo,
    'finalPrice' : IDL.Float64,
    'volumeDiscount' : IDL.Float64,
    'date' : IDL.Int,
    'town' : IDL.Text,
    'sector' : IDL.Text,
    'subSector' : IDL.Opt(IDL.Text),
    'grandTotal' : IDL.Float64,
    'addOns' : IDL.Vec(IDL.Text),
    'vatAmount' : IDL.Float64,
    'basePrice' : IDL.Float64,
    'services' : IDL.Vec(Service),
    'nightService' : IDL.Bool,
    'chargeDescription' : IDL.Text,
  });
  const BackupData = IDL.Record({
    'jobs' : IDL.Vec(Job),
    'expenses' : IDL.Vec(Expense),
    'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'contracts' : IDL.Vec(Contract),
    'serviceRates' : IDL.Vec(
      IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)))
    ),
    'timestamp' : IDL.Int,
    'invoices' : IDL.Vec(Invoice),
    'quotes' : IDL.Vec(Quote),
  });
  const MonthlyGoal = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Text,
    'achieved' : IDL.Bool,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'actualValue' : IDL.Float64,
    'targetValue' : IDL.Float64,
  });
  const FinancialMetrics = IDL.Record({
    'totalRevenueYTD' : IDL.Float64,
    'breakEvenProgress' : IDL.Float64,
    'investmentRemaining' : IDL.Float64,
    'netProfit' : IDL.Float64,
  });
  const ExpenseEntry = IDL.Record({
    'additionalInfo' : IDL.Text,
    'expenseId' : IDL.Nat,
    'date' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const JobRevenueEntry = IDL.Record({
    'revenue' : IDL.Float64,
    'clientName' : IDL.Text,
    'date' : IDL.Int,
    'jobId' : IDL.Nat,
    'sector' : IDL.Text,
  });
  const FundType = IDL.Variant({
    'main' : IDL.Null,
    'investment' : IDL.Null,
    'maintenance' : IDL.Null,
    'salaries' : IDL.Null,
  });
  const MaintenanceFundLedger = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Text,
    'date' : IDL.Int,
    'relatedJobId' : IDL.Opt(IDL.Nat),
    'fundId' : IDL.Nat,
    'fundType' : FundType,
    'remainingBalance' : IDL.Float64,
    'relatedExpenseId' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Float64,
    'purpose' : IDL.Text,
  });
  const MaintenanceFundStatus = IDL.Record({
    'balance' : IDL.Float64,
    'totalCollected' : IDL.Float64,
    'fundId' : IDL.Opt(IDL.Nat),
    'totalSpent' : IDL.Float64,
    'recentEntries' : IDL.Vec(MaintenanceFundLedger),
  });
  const FundTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'relatedJobId' : IDL.Opt(IDL.Nat),
    'fundId' : IDL.Nat,
    'fundType' : FundType,
    'remainingBalance' : IDL.Float64,
    'relatedExpenseId' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FundBalance = IDL.Record({
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'fundId' : IDL.Nat,
    'recentTransactions' : IDL.Vec(FundTransaction),
    'fundType' : FundType,
  });
  const FinancialMetricsDetailed = IDL.Record({
    'totalRevenueYTD' : IDL.Float64,
    'expenseBreakdown' : IDL.Vec(ExpenseEntry),
    'breakEvenProgress' : IDL.Float64,
    'investmentRemaining' : IDL.Float64,
    'revenueBreakdown' : IDL.Vec(JobRevenueEntry),
    'maintenanceFundStatus' : MaintenanceFundStatus,
    'fundBalances' : IDL.Vec(FundBalance),
    'netProfit' : IDL.Float64,
  });
  const CostBreakdown = IDL.Record({
    'revenue' : IDL.Float64,
    'cogs' : IDL.Float64,
    'additionalPilot' : IDL.Float64,
    'opEx' : IDL.Float64,
    'vanFuel' : IDL.Float64,
    'chemicals' : IDL.Float64,
    'profitMargin' : IDL.Float64,
    'generatorFuel' : IDL.Float64,
  });
  const InternalQuoteView = IDL.Record({
    'quote' : Quote,
    'costBreakdown' : CostBreakdown,
  });
  const MonthlyReport = IDL.Record({
    'jobsCompleted' : IDL.Nat,
    'month' : IDL.Text,
    'goalsAchieved' : IDL.Nat,
    'year' : IDL.Nat,
    'paidInvoices' : IDL.Nat,
    'vatCollected' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'goalsMissed' : IDL.Nat,
    'pendingInvoices' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'netProfit' : IDL.Float64,
  });
  const ServiceType = IDL.Variant({
    'windowCleaning' : IDL.Null,
    'solarPanelCleaning' : IDL.Null,
    'facadeWallCleaning' : IDL.Null,
    'roofCleaning' : IDL.Null,
    'fullBuildingCleaning' : IDL.Null,
  });
  const UserPreferences = IDL.Record({
    'metricFilters' : IDL.Vec(IDL.Text),
    'preferredLayout' : IDL.Text,
    'navigationPreferences' : IDL.Text,
    'darkMode' : IDL.Bool,
    'displayPreferences' : IDL.Text,
  });
  const DroneWashDashboard = IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addExpense' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addJob' : IDL.Func(
        [
          IDL.Float64,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          CustomerInfo,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'addMonthlyGoal' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backupData' : IDL.Func([], [BackupData], []),
    'createContract' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
        ],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createQuote' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(Service),
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          CustomerInfo,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteContract' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'deleteQuote' : IDL.Func([IDL.Nat], [], []),
    'getActiveContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getAllMonthlyGoals' : IDL.Func([], [IDL.Vec(MonthlyGoal)], ['query']),
    'getAllQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getAllServiceRates' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)))
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContract' : IDL.Func([IDL.Nat], [IDL.Opt(Contract)], ['query']),
    'getContractByClientName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Contract)],
        ['query'],
      ),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getFinancialMetrics' : IDL.Func([], [FinancialMetrics], ['query']),
    'getFinancialMetricsDetailed' : IDL.Func(
        [],
        [FinancialMetricsDetailed],
        ['query'],
      ),
    'getInternalQuoteView' : IDL.Func(
        [IDL.Nat],
        [InternalQuoteView],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getMonthlyExpenses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getMonthlyGoalsByMonthYear' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(MonthlyGoal)],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [MonthlyReport],
        ['query'],
      ),
    'getMonthlyRevenue' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'getProfitProjection' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getQuote' : IDL.Func([IDL.Nat], [IDL.Opt(Quote)], ['query']),
    'getServiceRate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Float64], ['query']),
    'getStandardizedServices' : IDL.Func([], [IDL.Vec(ServiceType)], ['query']),
    'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetMaintenanceFund' : IDL.Func([], [], []),
    'safeResetMaintenanceFundWithCashout' : IDL.Func([], [IDL.Float64], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserPreferences' : IDL.Func([UserPreferences], [], []),
    'setServiceRate' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'updateContract' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
        [],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          CustomerInfo,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateMonthlyGoal' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Float64], [], []),
    'updateQuote' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(Service),
          IDL.Float64,
          IDL.Vec(IDL.Text),
          IDL.Float64,
          IDL.Bool,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Text),
          CustomerInfo,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
  
  return DroneWashDashboard;
};

export const init = ({ IDL }) => { return []; };