/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackupData {
  'jobs' : Array<Job>,
  'expenses' : Array<Expense>,
  'userProfiles' : Array<[Principal, UserProfile]>,
  'contracts' : Array<Contract>,
  'serviceRates' : Array<[string, Array<[string, number]>]>,
  'timestamp' : bigint,
  'invoices' : Array<Invoice>,
  'quotes' : Array<Quote>,
}
export interface Contract {
  'id' : bigint,
  'endDate' : [] | [bigint],
  'clientName' : string,
  'createdBy' : Principal,
  'clientEmail' : string,
  'clientCompany' : string,
  'contractName' : string,
  'lastUpdated' : bigint,
  'agreedPrices' : Array<[string, number]>,
  'createdDate' : bigint,
  'clientPhone' : string,
  'areaTier' : string,
  'servicesCovered' : Array<string>,
  'contractStatus' : string,
  'startDate' : bigint,
}
export interface CostBreakdown {
  'revenue' : number,
  'cogs' : number,
  'additionalPilot' : number,
  'opEx' : number,
  'vanFuel' : number,
  'chemicals' : number,
  'profitMargin' : number,
  'generatorFuel' : number,
}
export interface CustomerInfo {
  'additionalInfo' : string,
  'jobType' : string,
  'name' : string,
  'town' : string,
  'coordinates' : string,
}
export interface DroneWashDashboard {
  'addExpense' : ActorMethod<[number, string, bigint, string], bigint>,
  'addFundTransaction' : ActorMethod<
    [bigint, number, string, string, string, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'addGoal' : ActorMethod<[string, string, bigint, string], bigint>,
  'addInvestmentFundTransaction' : ActorMethod<
    [number, string, string, string, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'addJob' : ActorMethod<
    [number, bigint, string, string, CustomerInfo, number, number],
    bigint
  >,
  'addMaintenanceExpense' : ActorMethod<
    [number, string, string, string, [] | [string], bigint],
    bigint
  >,
  'addMaintenanceFundLedgerEntry' : ActorMethod<
    [number, string, string, bigint, [] | [bigint], [] | [bigint]],
    bigint
  >,
  'addMonthlyGoal' : ActorMethod<[string, bigint, string, number], bigint>,
  'approveFundTransfer' : ActorMethod<[bigint, boolean], undefined>,
  'approveMaintenanceExpense' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backupData' : ActorMethod<[], BackupData>,
  'createContract' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      Array<[string, number]>,
      string,
      bigint,
      [] | [bigint],
    ],
    bigint
  >,
  'createFund' : ActorMethod<
    [FundType, string, number, number, number],
    bigint
  >,
  'createFundAlert' : ActorMethod<
    [bigint, string, number, number, string],
    bigint
  >,
  'createFundTransfer' : ActorMethod<[bigint, bigint, number, string], bigint>,
  'createInvoice' : ActorMethod<[string, string, bigint, number], bigint>,
  'createQuote' : ActorMethod<
    [
      string,
      Array<Service>,
      number,
      Array<string>,
      number,
      boolean,
      number,
      string,
      [] | [string],
      CustomerInfo,
      string,
      number,
      number,
    ],
    bigint
  >,
  'deleteContract' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteFund' : ActorMethod<[bigint], undefined>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'deleteQuote' : ActorMethod<[bigint], undefined>,
  'getActiveContracts' : ActorMethod<[], Array<Contract>>,
  'getAllContracts' : ActorMethod<[], Array<Contract>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllFundAlerts' : ActorMethod<[], Array<FundAlert>>,
  'getAllFundReports' : ActorMethod<[], Array<FundReport>>,
  'getAllFundTransactions' : ActorMethod<[], Array<FundTransaction>>,
  'getAllFundTransfers' : ActorMethod<[], Array<FundTransfer>>,
  'getAllFunds' : ActorMethod<[], Array<Fund>>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getAllInvestmentFundTransactions' : ActorMethod<
    [],
    Array<InvestmentFundTransaction>
  >,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getAllMaintenanceExpenses' : ActorMethod<[], Array<MaintenanceExpense>>,
  'getAllMaintenanceFundLedgerEntries' : ActorMethod<
    [],
    Array<MaintenanceFundLedger>
  >,
  'getAllMonthlyGoals' : ActorMethod<[], Array<MonthlyGoal>>,
  'getAllQuotes' : ActorMethod<[], Array<Quote>>,
  'getAllServiceRates' : ActorMethod<
    [],
    Array<[string, Array<[string, number]>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContract' : ActorMethod<[bigint], [] | [Contract]>,
  'getContractByClientName' : ActorMethod<[string], [] | [Contract]>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getFinancialMetrics' : ActorMethod<[], FinancialMetrics>,
  'getFinancialMetricsDetailed' : ActorMethod<[], FinancialMetricsDetailed>,
  'getFund' : ActorMethod<[bigint], [] | [Fund]>,
  'getFundAlertsByFundId' : ActorMethod<[bigint], Array<FundAlert>>,
  'getFundAnalytics' : ActorMethod<[bigint], FundAnalytics>,
  'getFundReport' : ActorMethod<[bigint], FundReport>,
  'getFundTransactionsByFundId' : ActorMethod<[bigint], Array<FundTransaction>>,
  'getFundTransfer' : ActorMethod<[bigint], [] | [FundTransfer]>,
  'getGoal' : ActorMethod<[bigint], [] | [Goal]>,
  'getInternalQuoteView' : ActorMethod<[bigint], InternalQuoteView>,
  'getInvestmentFund' : ActorMethod<[], InvestmentFund>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getMaintenanceExpense' : ActorMethod<[bigint], [] | [MaintenanceExpense]>,
  'getMaintenanceFundLedgerEntriesByFundId' : ActorMethod<
    [bigint],
    Array<MaintenanceFundLedger>
  >,
  'getMonthlyExpenses' : ActorMethod<[], Array<[string, number]>>,
  'getMonthlyGoalsByMonthYear' : ActorMethod<
    [string, bigint],
    Array<MonthlyGoal>
  >,
  'getMonthlyReport' : ActorMethod<[string, bigint], MonthlyReport>,
  'getMonthlyRevenue' : ActorMethod<[], Array<[string, number]>>,
  'getProfitProjection' : ActorMethod<[], Array<[bigint, number]>>,
  'getQuote' : ActorMethod<[bigint], [] | [Quote]>,
  'getServiceRate' : ActorMethod<[string, string], number>,
  'getStandardizedServices' : ActorMethod<[], Array<ServiceType>>,
  'getUserPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserPreferences' : ActorMethod<[UserPreferences], undefined>,
  'setServiceRate' : ActorMethod<[string, string, number], undefined>,
  'updateContract' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      Array<[string, number]>,
      string,
      bigint,
      [] | [bigint],
    ],
    undefined
  >,
  'updateExpense' : ActorMethod<
    [bigint, number, string, bigint, string],
    undefined
  >,
  'updateFund' : ActorMethod<
    [bigint, string, number, boolean, number, number],
    undefined
  >,
  'updateFundAlert' : ActorMethod<[bigint, boolean], undefined>,
  'updateGoal' : ActorMethod<[bigint, string, number], undefined>,
  'updateInvoice' : ActorMethod<
    [bigint, string, string, bigint, number, string],
    undefined
  >,
  'updateInvoiceStatus' : ActorMethod<[bigint, string], undefined>,
  'updateJob' : ActorMethod<
    [bigint, number, bigint, string, string, CustomerInfo, number, number],
    undefined
  >,
  'updateMonthlyGoal' : ActorMethod<[bigint, boolean, number], undefined>,
  'updateQuote' : ActorMethod<
    [
      bigint,
      string,
      Array<Service>,
      number,
      Array<string>,
      number,
      boolean,
      number,
      string,
      [] | [string],
      CustomerInfo,
      string,
      number,
      number,
    ],
    undefined
  >,
}
export interface Expense {
  'id' : bigint,
  'additionalInfo' : string,
  'date' : bigint,
  'category' : string,
  'amount' : number,
}
export interface ExpenseEntry {
  'additionalInfo' : string,
  'expenseId' : bigint,
  'date' : bigint,
  'category' : string,
  'amount' : number,
}
export interface FinancialMetrics {
  'totalRevenueYTD' : number,
  'breakEvenProgress' : number,
  'investmentRemaining' : number,
  'netProfit' : number,
}
export interface FinancialMetricsDetailed {
  'totalRevenueYTD' : number,
  'expenseBreakdown' : Array<ExpenseEntry>,
  'breakEvenProgress' : number,
  'investmentRemaining' : number,
  'revenueBreakdown' : Array<JobRevenueEntry>,
  'maintenanceFundStatus' : MaintenanceFundStatus,
  'fundBalances' : Array<FundBalance>,
  'netProfit' : number,
}
export interface Fund {
  'id' : bigint,
  'balance' : number,
  'name' : string,
  'lastUpdated' : bigint,
  'createdDate' : bigint,
  'isActive' : boolean,
  'spendingLimit' : number,
  'fundType' : FundType,
  'approvalThreshold' : number,
}
export interface FundAlert {
  'id' : bigint,
  'alertType' : string,
  'threshold' : number,
  'createdDate' : bigint,
  'isActive' : boolean,
  'fundId' : bigint,
  'currentValue' : number,
  'fundType' : FundType,
  'message' : string,
}
export interface FundAnalytics {
  'name' : string,
  'year' : bigint,
  'totalInflow' : number,
  'fundId' : bigint,
  'totalOutflow' : number,
  'fundType' : FundType,
  'monthlyTrends' : Array<[string, number]>,
  'netBalance' : number,
  'averageTransactionAmount' : number,
  'spendingByCategory' : Array<[string, number]>,
  'transactionCount' : bigint,
}
export interface FundBalance {
  'balance' : number,
  'name' : string,
  'fundId' : bigint,
  'recentTransactions' : Array<FundTransaction>,
  'fundType' : FundType,
}
export interface FundReport {
  'balance' : number,
  'name' : string,
  'year' : bigint,
  'totalInflow' : number,
  'fundId' : bigint,
  'reportDate' : bigint,
  'totalOutflow' : number,
  'fundType' : FundType,
  'monthlyTrends' : Array<[string, number]>,
  'netBalance' : number,
  'spendingByCategory' : Array<[string, number]>,
  'transactionCount' : bigint,
}
export interface FundTransaction {
  'id' : bigint,
  'transactionType' : string,
  'date' : bigint,
  'description' : string,
  'relatedJobId' : [] | [bigint],
  'fundId' : bigint,
  'fundType' : FundType,
  'remainingBalance' : number,
  'relatedExpenseId' : [] | [bigint],
  'category' : string,
  'amount' : number,
}
export interface FundTransfer {
  'id' : bigint,
  'status' : string,
  'date' : bigint,
  'approvedBy' : [] | [Principal],
  'sourceFundId' : bigint,
  'approvalDate' : [] | [bigint],
  'destinationFundId' : bigint,
  'amount' : number,
  'requestedBy' : Principal,
  'reason' : string,
}
export type FundType = { 'main' : null } |
  { 'investment' : null } |
  { 'maintenance' : null } |
  { 'salaries' : null };
export interface Goal {
  'id' : bigint,
  'milestoneTracking' : string,
  'description' : string,
  'targetMetrics' : string,
  'achievementStatus' : string,
  'progress' : number,
  'targetDate' : bigint,
}
export interface InternalQuoteView {
  'quote' : Quote,
  'costBreakdown' : CostBreakdown,
}
export interface InvestmentFund {
  'id' : bigint,
  'currentBalance' : number,
  'lastUpdated' : bigint,
  'createdDate' : bigint,
  'isActive' : boolean,
  'initialCapital' : number,
  'transactions' : Array<InvestmentFundTransaction>,
}
export interface InvestmentFundTransaction {
  'id' : bigint,
  'allocationType' : string,
  'transactionType' : string,
  'date' : bigint,
  'description' : string,
  'relatedJobId' : [] | [bigint],
  'remainingBalance' : number,
  'relatedExpenseId' : [] | [bigint],
  'amount' : number,
}
export interface Invoice {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'date' : bigint,
  'quoteId' : bigint,
  'totalAmount' : number,
  'customerEmail' : string,
}
export interface Job {
  'id' : bigint,
  'customerInfo' : CustomerInfo,
  'revenue' : number,
  'clientName' : string,
  'date' : bigint,
  'costs' : number,
  'sector' : string,
  'cleanProfit' : number,
}
export interface JobRevenueEntry {
  'revenue' : number,
  'clientName' : string,
  'date' : bigint,
  'jobId' : bigint,
  'sector' : string,
}
export interface MaintenanceExpense {
  'id' : bigint,
  'receiptUrl' : [] | [string],
  'date' : bigint,
  'createdBy' : Principal,
  'partCategory' : string,
  'equipmentType' : string,
  'fundId' : bigint,
  'approvalDate' : [] | [bigint],
  'fundType' : FundType,
  'approved' : boolean,
  'amount' : number,
  'purpose' : string,
}
export interface MaintenanceFundLedger {
  'id' : bigint,
  'transactionType' : string,
  'date' : bigint,
  'relatedJobId' : [] | [bigint],
  'fundId' : bigint,
  'fundType' : FundType,
  'remainingBalance' : number,
  'relatedExpenseId' : [] | [bigint],
  'amount' : number,
  'purpose' : string,
}
export interface MaintenanceFundStatus {
  'balance' : number,
  'totalCollected' : number,
  'fundId' : [] | [bigint],
  'totalSpent' : number,
  'recentEntries' : Array<MaintenanceFundLedger>,
}
export interface MonthlyGoal {
  'id' : bigint,
  'month' : string,
  'achieved' : boolean,
  'year' : bigint,
  'description' : string,
  'actualValue' : number,
  'targetValue' : number,
}
export interface MonthlyReport {
  'jobsCompleted' : bigint,
  'month' : string,
  'goalsAchieved' : bigint,
  'year' : bigint,
  'paidInvoices' : bigint,
  'vatCollected' : number,
  'totalExpenses' : number,
  'goalsMissed' : bigint,
  'pendingInvoices' : bigint,
  'totalRevenue' : number,
  'netProfit' : number,
}
export interface Quote {
  'id' : bigint,
  'customerInfo' : CustomerInfo,
  'finalPrice' : number,
  'volumeDiscount' : number,
  'date' : bigint,
  'town' : string,
  'sector' : string,
  'subSector' : [] | [string],
  'grandTotal' : number,
  'addOns' : Array<string>,
  'vatAmount' : number,
  'basePrice' : number,
  'services' : Array<Service>,
  'nightService' : boolean,
  'chargeDescription' : string,
}
export interface Service {
  'serviceType' : string,
  'rate' : number,
  'quantity' : number,
}
export type ServiceType = { 'windowCleaning' : null } |
  { 'solarPanelCleaning' : null } |
  { 'facadeWallCleaning' : null } |
  { 'roofCleaning' : null } |
  { 'fullBuildingCleaning' : null };
export interface UserPreferences {
  'metricFilters' : Array<string>,
  'preferredLayout' : string,
  'navigationPreferences' : string,
  'darkMode' : boolean,
  'displayPreferences' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE extends DroneWashDashboard {}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];